---
##
# Common tasks
#
- name: Add default variables per PHP version
  include_vars: "{{ item }}"
  with_items:
    - "php{{ php_version }}.yml"

- name: Install support for PHP.
  apt: pkg="{{ item }}" state=present
  with_items:
   - "{{ lamp_mod_php_package }}"

- name: Add site configuration file
  template: >
    src=site-ansible-default.j2 dest=/etc/apache2/sites-available/ansible-default{{ apache_site_file_suffix }} mode=644
  notify: restart apache

- name: Enable our new site
  command: >
    a2ensite ansible-default creates=/etc/apache2/sites-enabled/ansible-default{{ apache_site_file_suffix }}
  notify: restart apache

- name: Make sure old htpasswd file is gone
  file: path="/etc/apache2/htpasswd/{{ item.filename }}" state=absent
  with_items: apache_htpasswd + phpmyadmin_htpasswd + project_htpasswd
  when: item.filename is defined

- name: Creating htpasswd entries
  lineinfile: |
    line="{{ item.user }}:{{ item.password }}"
    dest="/etc/apache2/htpasswd/{{ item.filename }}"
    owner=root group=www-data mode=0640
    create=yes
  with_items: apache_htpasswd + phpmyadmin_htpasswd + project_htpasswd
  when: item.filename is defined

- include: phpmyadmin.yml
