---
##
# Common tasks
#
- name: Add default variables per PHP version
  include_vars: "{{ item }}"
  with_items:
    - "php{{ php_version }}.yml"

- name: Install support for PHP.
  apt: pkg="{{ item }}" state=present
  with_items:
   - "{{ lamp_mod_php_package }}"
