---
##
# Common tasks
#
- name: Add default variables per PHP version
  include_vars: "{{ item }}"
  with_items:
    - "php{{ php_version }}.yml"

- name: Cleanup any previous Apache PHP modules
  shell: >
    apt-get remove -y --purge $(dpkg --get-selections | cut -f1 | grep libapache2-mod-php | grep -v {{ lamp_mod_php_package }})
  register: result
  changed_when: "'Removing libapache2-mod-php' in result.stdout"

- name: Install support for PHP.
  apt: pkg="{{ item }}" state=present
  with_items:
   - "{{ lamp_mod_php_package }}"
