---
##
# PHPMyAdmin
#

- name: PHPMyAdmin | Install required packages.
  apt: pkg=phpmyadmin state=present update_cache=yes cache_valid_time=86400

- name: PHPMyAdmin | Adding site configuration
  template: >
    src=site-phpmyadmin.j2 dest=/etc/apache2/sites-available/phpmyadmin{{ apache_site_file_suffix }}
  notify: restart apache

- name: PHPMyAdmin | Enabling site
  command: >
    a2ensite phpmyadmin creates=/etc/apache2/sites-enabled/phpmyadmin{{ apache_site_file_suffix }}
  notify: restart apache

- name: PHPMyAdmin | Configuring PHPMyAdmin
  template: src=phpmyadmin-config-inc-php.j2 dest=/etc/phpmyadmin/config.inc.php mode=644

- name: PHPMyAdmin | Fix wrong symlinks
  command: |
    rm /usr/share/phpmyadmin/libraries/php-gettext/*
    ln /usr/share/php/php-gettext/* /usr/share/phpmyadmin/libraries/php-gettext
