# Ansible galaxy requirements for fetching all role dependencies that are not
# registered on galaxy.ansible.com.
---
- src: https://github.com/drunomics/ansible-role-base
  name: drunomics.base

- src: https://github.com/drunomics/ansible-role-apache
  name: drunomics.apache

- src: https://github.com/drunomics/ansible-role-mysql
  name: drunomics.mysql

- src: https://github.com/drunomics/ansible-role-php
  name: drunomics.php

- src: https://github.com/geerlingguy/ansible-role-adminer
  name: geerlingguy.adminer
